#version 460

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform sampler2D s_input;

layout (set = 1, binding = 0, r16f) uniform writeonly image2D s_output;


void main()
{
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(s_output);
	if (gid.x >= size.x || gid.y >= size.y)
		return;

	vec2 uv = (gid + 0.5) / vec2(size);
	vec3 color = texture(s_input, uv).rgb;

	float luminance = dot(color, vec3(0.2126, 0.7152, 0.0722));
	luminance = max(luminance, 0.0001);
    float logLuminance = log(luminance);

	imageStore(s_output, gid, vec4(logLuminance, 0, 0, 0));
}
