#version 460

#include "../common.glsl"

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform sampler2D s_depth;

layout (set = 1, binding = 0, rgba8) uniform writeonly image2D i_output;

layout (set = 2, binding = 0) uniform UniformBlock {
	mat4 projection;

#define outputSize imageSize(i_output).xy
};


vec3 reconstructPosition(vec2 uv, float depth)
{
	vec2 ndc = vec2(uv.x * 2 - 1, 1 - uv.y * 2);
	float near = projection[3][2];
	float x = projection[0][0];
	float y = projection[1][1];

	vec3 view;
	view.z = depth > 0 ? near / depth : 1000000;
	view.x = ndc.x * view.z / x;
	view.y = ndc.y * view.z / y;
	view.z *= -1; // right handed coordinate system
	return view;
}

vec3 getPosition(vec2 uv)
{
	float depth = textureLod(s_depth, uv, 0).r;
	return reconstructPosition(uv, depth);
}

vec3 getNormal(vec2 uv, vec3 position)
{
	vec2 texel = 1.0 / outputSize;

	vec3 right = getPosition(uv + vec2(texel.x, 0));
	vec3 left = getPosition(uv - vec2(texel.x, 0));
	vec3 top = getPosition(uv - vec2(0, texel.y));
	vec3 bottom = getPosition(uv + vec2(0, texel.y));

	vec3 dx0 = right - position;
	vec3 dx1 = position - left;

	vec3 tangent = abs(dx0.z) < abs(dx1.z) ? dx0 : dx1;

	vec3 dy0 = top - position;
	vec3 dy1 = position - bottom;

	vec3 bitangent = abs(dy0.z) < abs(dy1.z) ? dy0 : dy1;

	return normalize(cross(tangent, bitangent));
}

void main()
{
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(i_output);
	if (gid.x >= size.x || gid.y >= size.y)
		return;

	vec2 texel = 1.0 / size;
	vec2 uv = (gid + 0.5) * texel;

	float depth = textureLod(s_depth, uv, 0).r;
	if (depth == 0)
	{
		imageStore(i_output, gid, vec4(0));
		return;
	}

	vec3 position = reconstructPosition(uv, depth);
	vec3 normal = getNormal(uv, position);

	imageStore(i_output, gid, vec4(normal * 0.5 + 0.5, 0));
}
