#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(set = 1, binding = 0, rgba8) uniform writeonly image3D s_output;

#include "../common.glsl"
#include "noise.glsl"


void main()
{
	ivec3 gid = ivec3(gl_GlobalInvocationID.xyz);
	vec3 uvw = (gid + 0.5) / vec3(imageSize(s_output));

	float freq = 2;
	float L = 2.17;
	float P = 0.42;

	vec4 result;

	result.x = worleyFbm(uvw, freq, 4, L, P);
	result.y = worleyFbm(uvw, freq * pow(L, 4), 4, L, P);
	result.z = worleyFbm(uvw, freq * pow(L, 8), 4, L, P);

	imageStore(s_output, gid, result);
}
