#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(set = 1, binding = 0, r8) uniform writeonly image3D s_output;

#include "../common.glsl"
#include "noise.glsl"


float perlinWorley(vec3 p, float freq, float lacunarity, float persistence)
{
    float pfbm = perlinFbm(p, freq * 1, 3, lacunarity, persistence);
    float wfbm = worleyFbm(p, freq * 2.5, 3, lacunarity, persistence);
    return remap(pfbm, wfbm * 0.0, 1);
}

void main()
{
	ivec3 gid = ivec3(gl_GlobalInvocationID.xyz);
	vec3 uvw = (gid + 0.5) / vec3(imageSize(s_output));

	float freq = 4;
	float L = 2.17;
	float P = 0.42;

	//result.x = perlinWorley(uvw, freq);
    float x = perlinWorley(uvw, freq, L, P);
    float y = 1 - worleyFbm(uvw, freq * L, 3, L, P);
    float z = 1 - worleyFbm(uvw, freq * L * L, 3, L, P);
	float result = 0.625 * x + 0.25 * y + 0.125 * z;

	imageStore(s_output, gid, vec4(result, 0, 0, 0));
}
