#version 460

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D s_transmittanceLUT;
layout(set = 0, binding = 1) uniform sampler2D s_multiScatterLUT;
layout(set = 0, binding = 2) uniform sampler2D s_weatherMap;
layout(set = 0, binding = 3) uniform sampler3D s_cloudNoise;
layout(set = 0, binding = 4) uniform sampler3D s_cloudNoiseDetail;

layout(set = 1, binding = 0, r11f_g11f_b10f) uniform image2D s_output;

layout(set = 2, binding = 0) uniform UniformBlock {
	vec4 params;
	vec4 params2;

	vec4 weatherData;

#define sunDirection params.xyz
#define gameTime params.w
#define cameraPosition params2.xyz
};

#include "../common.glsl"
#include "sky.glsl"
#include "clouds.glsl"


void main()
{
	uint idx = gl_GlobalInvocationID.x;
	if (idx > 0)
		return;

	vec3 pos = cameraPosition + vec3(0, planetRadius, 0);
	float height = length(pos);
	vec3 up = pos / height;
	height -= planetRadius;

	float sunIntensity = 25;
	vec3 sunlight = sampleTransmittanceLUT(height, -sunDirection, up) * sunIntensity;

	vec4 cloudColor = clouds(cameraPosition, -sunDirection, sunDirection, 0, 0, 16);
	sunlight = sunlight * (1 - cloudColor.a);
	//vec3 sunlight = attenuateSun(cameraPosition, sunDirection);

	vec3 color = imageLoad(s_output, ivec2(0)).rgb;
	color = mix(color, sunlight, 0.01);

	imageStore(s_output, ivec2(0), vec4(color, 0));
}
