#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 1, binding = 0, rgba8) uniform writeonly image2D s_output;

#include "../common.glsl"
#include "noise.glsl"


float perlinWorley(vec3 p, float freq)
{
    float pfbm = perlinFbm(p, freq * 4, 7);
    float wfbm = 1 - worleyFbm(p, freq * 9, 8);
    return mix(1, pfbm, 0.9) * mix(1, wfbm, 0.7);

    //    + seamlessPerlin(p * freq * 2, freq * 2) * 0.25
    //    + seamlessPerlin(p * freq * 4, freq * 4) * 0.125;
    //float w = seamlessWorley(p * freq * 2, freq * 2);
    //return remap(pfbm, w * 0.5, 1, 0, 1);

    //float pfbm = perlinFbm(p, freq, 1);
    //float w = worleyNoise(p * freq, freq);
    //float n = remap(pfbm, 0, 1, w, 1);
    //n = max(n, 0);
    //return n;
}

float cloudType(vec3 p)
{
    float pfbm = perlinFbm(p, 1, 5);
               //+ 0.500 * (perlinFbm(p, 8, 3) - 0.5)
               //+ 0.250 * (perlinFbm(p, 16, 3) - 0.5);
    return clamp(pfbm * 11 - 5.2, 0, 1);
}

void main()
{
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	vec3 uvw = vec3((gid + 0.5) / vec2(imageSize(s_output)), 0);

	float freq = 4;

	vec4 result;

    result.x = cloudType(uvw);
	result.y = perlinWorley(uvw, 2);
    result.z = perlinWorley(uvw, 1);
    //result.y = 0.625 * perlinFbm(uvw, 1, 3)
    //         + 0.250 * perlinFbm(uvw, 1, 3)
    //         + 0.125 * perlinFbm(uvw, 1, 3);
	//result.y = 0.625 * worleyFbm(uvw, 15, 3)
    //         + 0.250 * worleyFbm(uvw, 19, 3)
    //         + 0.125 * worleyFbm(uvw, 23, 3) - 1;
	result.w = 1 - worleyFbm(uvw + 0.5, 9, 6);
	//result.w = worleyFbm(uvw, freq * 16, 3);

    /*
    float wfbm = result.y * 0.625 + result.z * 0.25 + result.w * 0.125;
    float cloud = remap(remap(abs(perlinFbm(uvw * 0.5, freq, 7)), 0, 1, worleyFbm(uvw * 0.5, freq), 1), wfbm - 1, 1, 0, 1);
    cloud = remap(cloud, 0.85, 1, 0, 1);
    result.x = cloud;
    */

	imageStore(s_output, gid, result);
}
