#version 460

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform sampler2D s_input0;
layout (set = 0, binding = 1) uniform sampler2D s_input1;

layout (set = 1, binding = 0, r11f_g11f_b10f) uniform writeonly image2D i_output;

layout(set = 2, binding = 0) uniform UniformBlock {
	vec4 params;

#define bloomStep int(params.x + 0.5)
};

#define KERNEL_SIZE 3


void main()
{
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(i_output);
	if (gid.x >= size.x || gid.y >= size.y)
		return;

	vec2 uv = (gid + 0.5) / vec2(size);

	int x0 = -(KERNEL_SIZE - 1) / 2;
	int x1 = x0 + KERNEL_SIZE - 1;
	int y0 = -(KERNEL_SIZE - 1) / 2;
	int y1 = y0 + KERNEL_SIZE - 1;

	vec3 result = vec3(0);
	for (int y = y0; y <= y1; y++)
	{
		for (int x = x0; x <= x1; x++)
		{
			vec2 offset = vec2(x, y) / textureSize(s_input0, 0);
			vec3 value = textureLod(s_input0, uv + offset, bloomStep + 1).rgb;
			result += value;
		}
	}

	vec3 input0 = result / (KERNEL_SIZE * KERNEL_SIZE);
	vec3 input1 = textureLod(s_input1, uv, bloomStep).rgb;

	imageStore(i_output, gid, vec4(input0 + input1, 0));
}
