#version 460

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform sampler2D s_input;

layout (set = 1, binding = 0, r16f) uniform writeonly image2D s_output;

layout(set = 2, binding = 0) uniform UniformBlock {
	vec4 params;

#define mip int(params.x + 0.5)
};


void main()
{
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(s_output);
	if (gid.x >= size.x || gid.y >= size.y)
		return;

	//vec2 texelSize = 1.0 / textureSize(s_input, mip - 1);
	//vec2 uv = (gid * 2 + 1) * texelSize;
	vec2 uv = (gid + 0.5) / vec2(size);

	float logLuminance = textureLod(s_input, uv, mip - 1).r;

	imageStore(s_output, gid, vec4(logLuminance, 0, 0, 0));
}
