#version 460

#include "../common.glsl"

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform sampler2D s_ssao;
layout (set = 0, binding = 1) uniform sampler2D s_depth;
layout (set = 0, binding = 2) uniform sampler2D s_normal;

layout (set = 1, binding = 0, r16f) uniform writeonly image2D i_output;

layout (set = 2, binding = 0) uniform UniformBlock {
	mat4 projection;
	vec4 params;

#define outputSize imageSize(i_output).xy
#define mip int(params.x + 0.5)
};


vec3 getNormal(vec2 uv, float lod)
{
	return normalize(textureLod(s_normal, uv, lod).rgb * 2 - 1);
}

void getSample(vec2 uv, float currentDist, vec3 currentNormal, out float value, out float weight)
{
	float depth = textureLod(s_depth, uv, mip).r;
	if (depth == 0)
	{
		value = 0;
		weight = 0;
		return;
	}

	float near = projection[3][2];
    float dist = depthToDistance(depth, near);
    vec3 normal = getNormal(uv, mip);

	float tz = 16;
	float depthDelta = abs(dist - currentDist) / currentDist;
	float depthWeight = pow(1.0 / (1 + depthDelta), tz);

	float tn = 8;
	float normalDelta = max(dot(currentNormal, normal), 0);
	float normalWeight = pow(normalDelta, tn);

    value = textureLod(s_ssao, uv, mip).r;
	weight = depthWeight * normalWeight;
}

void main()
{
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(i_output);
	if (gid.x >= size.x || gid.y >= size.y)
		return;

	vec2 texel = 1.0 / size;
	vec2 uv = (gid + 0.5) * texel;

	float depth = textureLod(s_depth, uv, mip).r;
	if (depth == 0)
	{
		imageStore(i_output, gid, vec4(0, 0, 0, 0));
		return;
	}

	vec3 normal = getNormal(uv, mip);

	float near = projection[3][2];
	float dist = depthToDistance(depth, near);

	float result = 0;
	float sum = 0;

	for (int y = -1; y <= 1; y++)
	{
		for (int x = -1; x <= 1; x++)
		{
			vec2 offset = vec2(x, y) * texel;

			float value;
			float weight;
			getSample(uv + offset, dist, normal, value, weight);

			result += weight * value;
			sum += weight;
		}
	}

	if (sum > 0.0001)
		result /= sum;

	imageStore(i_output, gid, vec4(result, 0, 0, 0));
}
